[package]
name = "parser"
version = "0.1.0"
edition = "2021"


[build-dependencies] 
lalrpop = "0.20.2"

[dependencies]
lexer = { path = "../lexer" }
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
